AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  http api

Globals:
  Function:
    Timeout: 60

Resources:
  LambdaFunctionHttp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.hello.Handler::handleRequest
      Runtime: java11
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /api
            Method: get