AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api gateway event

Parameters:
  BuildId:
    Type: String
    Default: unknown

Resources:
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Description: lambda api gateway event
      Handler: com.hello.Handler::handleRequest
      Runtime: java11
#      Policies: AmazonDynamoDBFullAccess
      MemorySize: 512
      Timeout: 60

      EventPattern:
        source:
          - "EventsForMyAPIdestination"
        State: "ENABLED"

      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api
            Method: get
#      VpcConfig:
#        SecurityGroupIds:
#        - sg-8bd7fefd
#        SubnetIds:
#        - subnet-a10e28ed

      Tags:
        owner: taixingbi
        projectname: Hello world
        application: demo
        exposure: private
        compliance: non-sensitive
        banner: s5a
